import type { SiteContent } from "@/types/content";

/**
 * Social handles, in one place because the footer and the contact section both
 * need them and a second copy is a second thing to get wrong.
 *
 * `.example` is the IANA-reserved placeholder name, used here for the same
 * reason the phone number and the WhatsApp number are unassigned: these must
 * read unmistakably as stand-ins and must not resolve to some real account that
 * would then be associated with a fictional brand. They are structurally valid
 * links — the pattern is demonstrated — that simply do not lead anywhere.
 */
const HANDLE = "parnian.example";

const social = {
  instagram: { label: "اینستاگرام", href: `https://instagram.com/${HANDLE}` },
  telegram: { label: "تلگرام", href: `https://t.me/${HANDLE}` },
  pinterest: { label: "پینترست", href: `https://pinterest.com/${HANDLE}` },
};

/**
 * PLACEHOLDER CONTENT — Phase 01.
 *
 * The brand name, contact details and social handles below are stand-ins so the
 * layout can be reviewed with realistic Persian text. Phone and email are
 * deliberately non-functional. Nothing here asserts a fact about a real
 * business; replace the whole object when the client supplies their details.
 */
export const site: SiteContent = {
  brand: {
    name: "پرنیان",
    latin: "PARNIAN",
    line: "مجموعه‌ای کوچک از محصولات مراقبت روزمره از پوست.",
  },

  /**
   * Document title for the site as a whole. `titleTemplate` wraps whatever a
   * route supplies, so the brand name is written once here rather than being
   * repeated into every page's `<title>` by hand.
   */
  seo: {
    title: "پرنیان — مراقبت روزمره از پوست",
    titleTemplate: "%s — پرنیان",
    description:
      "پرنیان مجموعه‌ای کوچک از محصولات مراقبت روزمره از پوست است؛ پنج محصول برای یک روتین کامل، از پاک‌کننده تا سرم شب.",
    /**
     * Generated by `scripts/generate-og.mjs` — a PNG, not an SVG like every
     * other image here, because no social crawler renders an SVG share card.
     */
    ogImage: {
      src: "/media/og-card.png",
      alt: "نشان پرنیان روی زمینهٔ سرمه‌ای",
      width: 1200,
      height: 630,
    },
  },

  /**
   * Navigation, mid-migration by design.
   *
   * Every entry is a real destination now. «تماس با ما» deep-links to the
   * contact block on the about page rather than getting a route of its own:
   * the brand has one short story and one set of contact details, which is a
   * page, not two (§19 — do not force five pages if the content needs fewer).
   *
   * Hrefs are written from the site root so the header works on every page —
   * a bare `#contact` resolves against whatever page the header happens to be
   * rendered on, which is nothing at all outside the homepage.
   */
  nav: [
    { label: "محصولات", href: "/products/" },
    { label: "گالری", href: "/gallery/" },
    { label: "دربارهٔ ما", href: "/about/" },
    { label: "تماس با ما", href: "/about/#contact" },
  ],

  headerCta: { label: "دریافت مشاوره", href: "/about/#contact" },

  contact: {
    city: "تهران",
    phone: "۰۲۱ — ۰۰۰۰ ۰۰۰۰",
    phoneHref: "+982100000000",
    /**
     * WhatsApp number for click-to-chat, in Latin digits with no punctuation —
     * `wa.me` accepts nothing else, and Persian digits are not matched by `\d`
     * (§36.5, the bug that produced empty `tel:` links in Phase 01).
     *
     * Deliberately not a real number, like the phone and email above. `wa.me`
     * answers an unassigned number with "this link is invalid" rather than
     * opening a chat with a stranger, which is the correct behaviour for a
     * placeholder.
     */
    whatsapp: "989000000000",
    email: "hello@parnian.example",
    /** Secondary inquiry path (§42), for brand-discovery rather than a product question. */
    instagram: { handle: `@${HANDLE}`, href: social.instagram.href },
  },

  social: [social.instagram, social.telegram, social.pinterest],

  /**
   * Empty on purpose, and the footer hides the row while it is.
   *
   * These were «حریم خصوصی» and «شرایط استفاده» pointing at `href="#"` — links
   * that focus like links and jump the reader to the top of the page. The fix
   * is not to write the pages: a privacy policy and terms of use are the one
   * category of content where inventing plausible text is actively harmful,
   * and §44.1 rules out far less consequential fabrications than that.
   *
   * Add real entries here when real policies exist and the row comes back with
   * no change to any component.
   */
  legal: [],

  /** The two column headings in the footer — brand copy, not structure. */
  footer: {
    navHeading: "مجموعه",
    contactHeading: "تماس",
  },

  copyright: "© ۱۴۰۵ پرنیان — تمام حقوق محفوظ است.",
};
